# This takes approach of ValueError generated by transformation of int(value)
def is_valid_ip(strng: str):
    octets_list = strng.split('.')
    if len(octets_list) != 4 or ' ' in strng or '\n' in strng:
        return False
    else:
        for octet in octets_list:
            try:
                if not (0 <= int(octet) <= 255) or (octet[0] == '0' and len(octet) > 1):
                    return False
            except ValueError:
                return False
    return True
